simple_social/posts/urls.py
from django.urls import include, path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),

]

simple_social/simple_social/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('success/', views.SuccessPage.as_view(), name='success'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
    
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

simple_social/posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
import markdown
from groups.models import Group
from django.contrib.auth import get_user_model


# Create your models here.
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    # ForeignKey to User model
    # related_name='posts': User.posts accesses all their posts
    created_at = models.DateTimeField(auto_now_add=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return self.message
    
    def save(self, *args, **kwargs):
        self.message_html = markdown.markdown(self.message)
        super().save(*args, **kwargs)
        # Calls parent class save()

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={
            'username': self.user.username,  # Access via the user ForeignKey
            'pk': self.pk
        })
    
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

simple_social/posts/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin
# Optimizes database queries using select_related
# Reduces number of DB queries for related objects

from . import models

from django.contrib.auth import get_user_model


# Create your views here.
User = get_user_model()


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')


class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context
    

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))
        # The related user's username (case-insensitive)


class DeletePost(LoginRequiredMixin, UserPassesTestMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('groups:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def test_func(self):
        post = self.get_object()
        return self.request.user.is_superuser or post.user == self.request.user

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

simple_social/posts/templates/posts/_post.html
<div class="post-container">
    <!-- Post Content -->
    <div class="post-content-box">
        {{ post.message_html|safe }}
    </div>

    <!-- Post Metadata -->
    <div class="post-meta-container">
        <div class="post-author-info">
            <a href="{% url 'posts:for_user' username=post.user.username %}" class="author-link">
                <span class="author-avatar">{{ post.user.username|slice:":1"|upper }}</span>
                <span class="author-name">@{{ post.user.username }}</span>
            </a>
        </div>

        {% if post.group %}
        <div class="post-group-info">
            <span class="group-prefix">in</span>
            <a href="{% url 'groups:single' slug=post.group.slug %}" class="group-link">
                {{ post.group.name }}
            </a>
        </div>
        {% endif %}

        <div class="post-time-info">
            <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}" class="time-link">
                {{ post.created_at|date:"M j, Y" }}
            </a>
        </div>
    </div>

    <!-- Post Actions -->
    {% if user.is_authenticated and post.user == user %}
    <div class="post-actions-container">
        <a href="{% url 'posts:delete' pk=post.pk %}" class="delete-btn">
            <i class="delete-icon"></i>
            <span>Delete</span>
        </a>
    </div>
    {% endif %}
</div>

simple_social/posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            {% block pre_post %}{% endblock %}
            {% block post_content %}{% endblock %}
            {% block post_post %}{% endblock %}
        </div>
    </div>
{% endblock %}

simple_social/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}
{% load static %}


{% block post_content %}
<div class="delete-confirmation">
    <div class="warning-icon">
        <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path>
            <line x1="12" y1="9" x2="12" y2="13"></line>
            <line x1="12" y1="17" x2="12" y2="17"></line>
        </svg>
    </div>
    
    <h3>Are you sure you want to delete this post?</h3>
    <p class="text-muted">This action cannot be undone</p>
    
    <div class="post-preview">
        {% include "posts/_post.html" with post=object hide_delete=True %}
    </div>

    <form method="POST" action="{% url 'posts:delete' pk=object.pk %}">
        {% csrf_token %}
        <div class="confirmation-actions">
            <button type="submit" class="btn-delete">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="margin-right: 8px; vertical-align: middle;">
                    <path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
                </svg>
                Confirm Delete
            </button>
            <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn-cancel">
                Cancel
            </a>
        </div>
    </form>
</div>
{% endblock %}

simple_social/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% load static %}

{% block post_content %}
<div class="post-detail-container">
    <div class="post-content">
        {{ post.message_html|safe }}
    </div>

    <div class="post-meta">
        <div class="post-author">
            <div class="author-avatar">
                {{ post.user.username|slice:":1"|upper }}
            </div>
            <a href="{% url 'posts:for_user' username=post.user.username %}">
                @{{ post.user.username }}
            </a>
        </div>

        {% if post.group %}
        <div class="post-group">
            <span>in</span>
            <a href="{% url 'groups:single' slug=post.group.slug %}">
                {{ post.group.name }}
            </a>
        </div>
        {% endif %}

        <div class="post-time">
            <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">
                {{ post.created_at|date:"F j, Y" }}
            </a>
        </div>
    </div>

    {% if user.is_authenticated and post.user == user %}
    <div class="post-actions">
        <a href="{% url 'posts:delete' pk=post.pk %}" class="delete-btn">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
            </svg>
            Delete Post
        </a>
    </div>
    {% endif %}
</div>
{% endblock %}

simple_social/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}

{% block post_content %}
    <h4>Create a new post!</h4>
    <form action="{% url 'posts:create' %}" method="POST" id="post_form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-large" value="Post">
    </form>
{% endblock %}

simple_social/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}
{% load static %}

{% block title %}{{ post_user.username }}'s Posts | Simpler{% endblock %}

{% block pre_post %}
<div class="profile-header">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-2 col-4">
                <div class="profile-avatar">
                    <div class="avatar-circle">
                        {{ post_user.username|slice:":1"|upper }}
                    </div>
                </div>
            </div>
            <div class="col-md-7 col-8">
                <h1 class="profile-username">
                    <i class="fas fa-user-circle me-2"></i>
                    @{{ post_user.username }}
                </h1>
                <p class="profile-stats">
                    <i class="fas fa-file-alt me-1"></i>
                    {{ post_list.count }} post{{ post_list.count|pluralize }}
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block post_content %}
<div class="container">
    {% if post_list %}
    <div class="row">
        {% for post in post_list %}
        <div class="col-lg-6 col-md-12 mb-4">
            <div class="post-card card h-100">
                <div class="card-body">
                    {% include "posts/_post.html" %}
                </div>
                <div class="card-footer bg-white border-top-0 pt-0">
                    <small class="text-muted">
                        <i class="far fa-clock me-1"></i>
                        {{ post.created_at|timesince }} ago
                    </small>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="empty-state">
        <div class="empty-state-icon">
            <i class="fas fa-file-alt"></i>
        </div>
        <h3>No Posts Yet</h3>
        <p>
            {% if user == post_user %}
            Your creative space is empty. Share your first thought with the world!
            {% else %}
            @{{ post_user.username }} hasn't shared anything yet.
            {% endif %}
        </p>
        {% if user == post_user %}
        <a href="{% url 'posts:create' %}" class="btn btn-primary px-4 py-2">
            <i class="fas fa-plus me-2"></i>Create Post
        </a>
        {% endif %}
    </div>
    {% endif %}
</div>
{% endblock %}